language: node_js
node_js:
  - 13
services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - docker image prune --all --force

script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-feed fotso0244/udagram-api-feed:v5
  - docker tag udagram-api-user fotso0244/udagram-api-user:v5
  - docker tag udagram-frontend fotso0244/udagram-frontend:v5
  - docker tag udagram-reverseproxy fotso0244/udagram-reverseproxy:v4

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push fotso0244/udagram-api-feed:v5
  - docker push fotso0244/udagram-api-user:v5
  - docker push fotso0244/udagram-frontend:v5
  - docker push fotso0244/udagram-reverseproxy:v4
