apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-backend-feed
  labels:
    app: udagram-backend-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-backend-feed
  template:
    metadata:
      labels:
        app: udagram-backend-feed
    spec:
      containers:
      - name: udagram-backend-feed
        image: fotso0244/udagram-api-feed:v2
        resources:
          requests:
            memory: "500Mi"
          limits:
            memory: "1000Mi"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
