apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-backend-feed
  labels:
    app: udagram-backend-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-backend-feed
  template:
    metadata:
      labels:
        app: udagram-backend-feed
    spec:
      containers:
      - name: udagram-backend-feed
        image: fotso0244/udagram-api-feed:v5
        envFrom:
        - configMapRef:
            name: env-configmap
        - secretRef:
            name: postgre
        resources:
          requests:
            memory: "1Gi"
          limits:
            memory: "2Gi"
        ports:
        - containerPort: 8080
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 300
          periodSeconds: 10
