apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend
  labels:
    app: udagram-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-frontend
  template:
    metadata:
      labels:
        app: udagram-frontend
    spec:
      containers:
      - name: udagram-frontend
        image: fotso0244/udagram-frontend:v4
        envFrom:
        - configMapRef:
            name: env-configmap
        - secretRef:
            name: postgre
        resources:
          requests:
            memory: "1Gi"
          limits:
            memory: "2Gi"
        ports:
        - containerPort: 8100
