apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: public-access-frontend
spec:
  podSelector:
    matchLabels:
      app: udagram-frontend
  securityGroups:
    groupIds:
      - sg-0f4f204e03f00821d
